apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lineq
    app.ap.deploy: lineq
  name: lineq-deployment
  namespace: lineq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.ap.deploy: lineq
  template:
    metadata:
      annotations:
        prometheus.io/port: "9000"
        prometheus.io/scrape: "false"
      labels:
        app: lineq
        app.ap.deploy: lineq
    spec:
      containers:
        - name: lineq
          image: h6m9d/lineq:latest
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - mountPath: /etc/lineq
            name: lineq-config-volume

        volumes:
        - name: lineq-config-volume
          configMap:
            name: lineq-cm
      imagePullSecrets:
        - name: lineq-reg
      restartPolicy: Always
