# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Go App

on:
  push:
    tags:
      - 'v*-release'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.20.x]
        os: [linux]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build Go App
      run: |
        go build -ldflags '-w -extldflags "-static"' -o lineq  

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lineq-${{ matrix.os }}
        path: lineq
